server:
  port: 1000


spring:
  redis:
    database: 3
    host: 192.168.2.169
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数（负值表示无限制）
        max-active: 8
        # 连接池最大阻塞等待时间（负值无限制)
        max-wait: 5000
        # 最大空闲链接数
        max-idle: 8
        # 最小空闲链接数
        min-idle: 1

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      idle-timeout: 600000 #空闲连接存活最大时间，默认600000
      maximum-pool-size: 30
      auto-commit: true #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      pool-name: DemoQuartzHikariCP
      max-lifetime: 900000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
    #JDBC基本配置
    url: jdbc:mysql://192.168.2.169:3306/user_center?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/html/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix: .html
    #encoding: UTF-8
    #content-type: text/html
    mode: HTML5

oauth:
  base_address: http://localhost:1000
  get_token_url: ${oauth.base_address}/oauth/token?
  scopo: all
  clientId: xlm
  clientSecret: $2a$10$REQ4KGHvWyvVhisMuTXTbOwIOnf2nn/6I7NVCkuTGuOqisLnYm2R2